### ISSUE TITLE
Не работает в сафари (storage)

### ISSUE THREAD

**Issue by f2re** [Feverqwe/Mono#1]
Удобная библиотека! 
не работает в сафари (Версия 7.1.4 (9537.85.13.7)) хранилище mono.storage
на скриншоте приложил кусок кода и то, что в консоли выходит.

т.е. получается, объект mono  создается, но в callback не заходит. Ошибок не выдает.

![2015-03-28 16 53 00](https://cloud.githubusercontent.com/assets/9370823/6881315/e954d82c-d56a-11e4-957c-3892b60f1738.png)
![2015-03-28 16 53 00 2](https://cloud.githubusercontent.com/assets/9370823/6881316/eb1b04d8-d56a-11e4-8d05-4adba79f9eda.png)

**Comment by Feverqwe** [comment]
Хай. А на фоновой странице monо сoобщения слушает? Должно хоть что то слушать. Т.к. хранилище работает через сообщения.

**Comment by f2re** [comment]
да, привет =)
вот на фоновой (та, что начальные скрипты) вызываю mono.sendMessageToActiveTab({name:"clickedButton",enable:false});

и почему-то срабатывает storage на той странице. ( в консоли выводит объект storage) но возникает ошибка в библиотеке (не находит чего-то там)

![2015-03-28 17 54 00](https://cloud.githubusercontent.com/assets/9370823/6881516/4cd2c262-d573-11e4-8cb3-d00275f85bf1.png)

**Comment by Feverqwe** [comment]
Вы отсылаете сообщение в активную вкладку, когда ее нету. Т.е. нету объекта safari.application.activeBrowserWindow.activeTab (можете поставить вручную условие и вызывать метод когда объект есть)
Хранилище начинает работать потому, что фоновая страница автоматически начинает слушать сообщения (если до этого вы не поставили обработчик), что бы получить ответ на отправленное сообщение. 

В общем что бы слушать сообщения можно добавить просто вот это:

``` javascript
mono.onMessage(function(msg, cb) {
});
```

**Comment by f2re** [comment]
я правильно понял, что надо на фоновую страницу добавить пустой onMessage, чтобы все заработало?)

**Comment by Feverqwe** [comment]
Да, для хранилища этого хватит.
28 Мар 2015 г. 20:25 пользователь "f2re" notifications@github.com написал:

**Comment by f2re** [comment]
Благодарю!
